# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
