# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20171016_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media cdn'),
        ),
    ]
