# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20171024_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.CharField(blank=True, default='Placeholder Content', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='Placeholder Content', max_length=50),
        ),
    ]
